source: .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess']
exclude:     ['README.md']
keep_files:  ['.git', '.svn']

# github overrides some values as follows
safe: true
lsi: false
highligther: rouge


redcloth:
  hard_breaks: false
