source: .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['README.md']
keep_files:  ['.git', '.svn']
timezone: Europe/Brussels

# github overrides some values as follows
safe: true
lsi: false
pygments: true


redcloth:
  hard_breaks: false